package aero.alsalam.jparelationshipsamples.entities;


import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

@Entity
public class Student {
	
	public Student() {
		super();
		// TODO Auto-generated constructor stub
	}


	@Id
	// If seq name not given then they will share the same sequence
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "student_seq") 
	private Long id;
	
	private String name;

	@OneToOne
	private Passport passport;
	
	@ManyToMany
	//This will fix the name and column names of the autogenerated table
	@JoinTable(
	        name="STUDENT_COURSE",
	        joinColumns=
	            @JoinColumn(name="STUDENT_ID"),
	        inverseJoinColumns=
	            @JoinColumn(name="COURSE_ID")
	    )
	private List<Course> courses=new ArrayList<>();
	
	@OneToMany(mappedBy="student")
	private List<Review> reviews=new ArrayList<>();
	
	public Student(String name) {
		super();
		this.name = name;
	}

	
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}



	public Long getId() {
		return id;
	}


	public Passport getPassport() {
		return passport;
	}


	public void setPassport(Passport passport) {
		this.passport = passport;
	}


	public void setId(Long id) {
		this.id = id;
	}

	public List<Course> getCourses() {
		return courses;
	}


	public void addCourse(Course course) {
		courses.add(course);
	}
	
	public List<Review> getReviews() {
		return reviews;
	}
	
	public void addReview(Review review) {
		reviews.add(review);
	}

	@Override
	public String toString() {
		return "Student [id=" + id + ", name=" + name + ", passport=" + passport + "]";
	}
	
}
